name: release-binaries
on:
  release:
    types: [published]
env:
  BINARY_NAME: media-cleaner
jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-musl
          use-cross: true

      - name: Optimize and package binary
        run: |
          cd target/x86_64-unknown-linux-musl/release
          strip ${{ env.BINARY_NAME }}
          chmod +x ${{ env.BINARY_NAME }}
          tar -c ${{ env.BINARY_NAME }} | gzip > ${{ env.BINARY_NAME }}.tar.gz

      - name: Upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: ${{ env.BINARY_NAME }}-${{ github.event.release.tag-name }}-linux-x86_64.tar.gz
          asset_path: target/x86_64-unknown-linux-musl/release/${{ env.BINARY_NAME }}.tar.gz
          upload_url: ${{ github.event.release.upload_url }}

  macos-x86_64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
          use-cross: true

      - name: Optimize and package binary
        run: |
          cd target/release
          strip ${{ env.BINARY_NAME }}
          chmod +x ${{ env.BINARY_NAME }}

      - name: Upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: ${{ env.BINARY_NAME }}-${{ github.event.release.tag-name }}-macos-x86_64.dmg
          asset_path: target/release/${{ env.BINARY_NAME }}.dmg
          upload_url: ${{ github.event.release.upload_url }}

  windows-x86_64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
          use-cross: true

      - name: Upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: ${{ env.BINARY_NAME }}-${{ github.event.release.tag-name }}-windows-x86_64.exe
          asset_path: target/release/${{ env.BINARY_NAME }}.exe
          upload_url: ${{ github.event.release.upload_url }}
